name: cs1332_downloader
description: An automated way to download student tests for CS1332.
version: 0.0.1
author: Pranav Nutalapati
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  dart_app_data: ^1.0.1
  dio: ^3.0.0
  prompts: ^1.3.1
  args: ^1.6.0
  path: ^1.7.0
  io: ^0.3.5